### ISSUE TITLE
Implement 'WorldWind Viewer' into WWSK

### ISSUE THREAD

**Issue by Beak-man** [NASAWorldWind/WorldWindServerKit#107]
Deriving from the work on #90, implement a full-featured Web WorldWind-based asset viewer inside WWSK. This will complement (functionally speaking it may substitute) the current 'Layer Preview' features that were inherited from GeoServer, enabling WWSK to operate as a complete end-to-end solution for end users.

Two routes to implement the viewer should be considered:

~- Making it part of the rest of WWSK's admin web panel (this is, a web application built under Apache Wicket/FreeMarker)~
- Building a complete separate web application, with its toolset at our discretion

![viewer use case diagram](https://user-images.githubusercontent.com/191515/30445598-5ad8bd56-993b-11e7-8a60-237c15a07210.png)

- [x] Layer Manager model
- [x] Layer Manager UI
- [ ] Server-side settings 
    - [x] Viewer menu link 
    - [ ] Default layers
    - [ ] WMS Version
    - [ ] Endpoint (WMS or GWC)
    - [x] Vendor params (e.g., tiled=true)
- [x] Session-based settings (client)
- [x] URL based initialization

**Comment by emxsys** [comment]
Added a high-level use case diagram to the epic.

**Comment by emxsys** [comment]
Added a prototype viewer--the Explorer--to WWSK.  The Explorer includes a layer manager that exposes the layers found in the GeoServer's WMS GetCapabilites document in a sortable list that includes persistence between sessions. The Explorer includes the ability to "zoom" to a selected layer.  The Explorer includes the capability to generate and copy a URL containing the active layers to the clipboard as the basis for a "bookmark" or sharable link.
