### ISSUE TITLE
Deploy, test and support followup

### ISSUE THREAD

**Issue by emxsys** [NASAWorldWind/WorldWindServerKit#124]
Several improvements to the WWSK test framework are needed to assure quality and performance.  The tests should be capable of running in a continuous integration environment.

- [x] Run the JMeter tests from the command-line or via Maven #128 
- [x] Create a test runner that configures the environment for JAI and GDAL #130  
- [x] Add a redistributable test data set to the WWSK project #127 
- [x] Refactor JMeter _GeoServer Functional Tests_ to use assertions #125 
- [x] Document test procedures #123

**Comment by emxsys** [comment]
### JMeterMavenPlugin
Consider using the JMeterMavenPlugin: https://wiki.apache.org/jmeter/JMeterMavenPlugin
