### ISSUE TITLE
Refactor the WWSK Explorer packaging

### ISSUE THREAD

**Issue by emxsys** [NASAWorldWind/WorldWindServerKit#154]
The Explorer should be packaged and distributed as an standard HTML5/JavaScript web app instead of a GeoServer jar.  This would allow _easy_ customization of the Explorer without the need to compile WWSK modules. 

### Serve the WWSK Explorer web app via GeoServer's static web pages
- [x] Add Explorer resources to distribution assemblies
- [x] Add Explorer resources to integration tests
- [x] Add Explorer resources to war file
- [x] Update Explorer link in GeoServer admin
- [x] Update Explorer link in About WWSK page

@TrilliumLearning

**Comment by emxsys** [comment]
### Options
The WWSK Explorer is a HTML5/JavaScript single-page web app accessed via `index.html` in a folder named `explorer`

#### Serve the WWSK Explorer via Jetty
Place the `explorer` web app folder in the Jetty `webapps` folder alongside `geoserver`
```
worldwind-geoserver/
    webapps/
        explorer
        geoserver
```
#### Serve the WWSK Explorer web app via GeoServer
[Serving Static Files](http://docs.geoserver.org/latest/en/user/tutorials/staticfiles.html)
> You can place static files in the www subdirectory of the GeoServer data directory, and they will be served at http:/myhost:8080/geoserver/www. This means you can deploy HTML, images, or JavaScript, and have GeoServer serve them directly on the web.

Copy the explorer web app folder into a `www` folder under the `data_dir` folder
```
worldwind-geoserver/
    data_dir/
        www/
            explorer
 ````

**Comment by emxsys** [comment]
### Tasks
- [ ] Distribute Explorer to `worldwind-geoserver/data_dir/www/explorer`
- [ ] Redirect Explorer menu entry to `/geoserver/www/explorer.index.html`

**Comment by emxsys** [comment]
The WWSK Explorer now resides in the `GEOSERVER_DATA_DIR/www/explorer` folder. The web app source code in this folder can be now be modified and updated by GeoServer admins outside the WWSK build process.

**Comment by emxsys** [comment]
The integration tests are failing to find `/geoserver/www/explorer/index.html` whereas the functional test are working fine.

**Comment by emxsys** [comment]
- Add Explorer resources to distribution assemblies
- Add Explorer resources to integration tests
- Add Explorer resources to war file
- Update Explorer link in GeoServer admin
- Update Explorer link in About WWSK page
