### ISSUE TITLE
Develop WWSK production server

### ISSUE THREAD

**Issue by emxsys** [NASAWorldWind/WorldWindServerKit#65]
### Objectives
- [ ] Compatibility with existing WWJ clients 
- [ ] Optimize source data
- [ ] Document best practices 
- [ ] WMS imagery/maps
- [ ] Cascaded WMS for USGS maps 
- [ ] WMTS imagery/maps
- [ ] WCS elevations
- [ ] WFS placenames

### Tasks
- [ ] Prepare source imagery
- [ ] Prepare source elevations
- [ ] Prepare source placenames
- [ ] Configure GeoWebCache
